name: Validate Go Mod Files

on:
  pull_request:
  merge_group:

jobs:
  go-mod-validation:
    name: Validate go.mod dependencies
    runs-on: ubuntu-latest
    # Skip on merge group events
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v6

      - name: Validate go.mod
        uses: smartcontractkit/.github/apps/go-mod-validator@go-mod-validator/v1
        with:
          repo-branch-exceptions: |
            smartcontractkit/chainlink-ccip:develop
            smartcontractkit/chainlink-sui:2.31.0-cherry-picked
            smartcontractkit/chainlink-protos:capabilities-development
            smartcontractkit/cre-sdk-go:capabilities-development
            smartcontractkit/cre-sdk-typescript:capabilities-development
          repo-sha-exceptions: |
            smartcontractkit/chainlink-aptos:c2a8d09e5b46c1c7815700f645a50caf8a466bda
            smartcontractkit/chainlink-ccip:87778cfb9fd3ef44f0ff21b237b39b321219987a
            smartcontractkit/chainlink-ccip:653e567258548f98a2a650399fd56b3190d1000e
